pipeline {
    agent any
    tools {nodejs 'NodeJs'}
    stages {
        stage("Install"){
            steps{
                sh "npm install"
            }
        }
    }
    // stage("Build"){
    // steps{
    //    sh "npm run build"
    // }}
    stage("Deploy"){
        steps {
            sh "rm -rf /usr/local/var/www/node-app"
            sh "cp -R /Users/aakash/.jenkins/workspace/weatherappnode /usr/local/var/www/node-app"
        }
    }

}